chartmuseum:
  persistence:
    enabled: true
  env:
    open:
      DISABLE_API: false
    existingSecret: chartmuseum-secret
    existingSecretMappings:
      BASIC_AUTH_USER: basic-auth-user
      BASIC_AUTH_PASS: basic-auth-pass
